// <auto-generated />
namespace Jupiter.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_usuario_perfil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_usuario_perfil));
        
        string IMigrationMetadata.Id
        {
            get { return "201709130400084_create_usuario_perfil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
